### ISSUE TITLE
Not able to use uppercase prefixes

### ISSUE THREAD

**Issue by titenis** [barzik/branch-name-lint#27]
First of all you lowercase both the prefix and the rest of the name:
```
const prefix = parts[0].toLowerCase();
let name = null;
if (parts[1]) {
      name = parts[1].toLowerCase();
}
```
then you check lowercased prefix with unaltered prefixes array:
```
if (this.options.prefixes.includes(prefix) === false) {
```

It makes me wonder why you even do lowercasing? Why not make it stricter since this lib is all about strict branch name rules? Or at least add an option to disable lowercasing

**Comment by barzik** [comment]
Actually, never gave a real thought about it. In the old times, Git was really problematic around capital letters. I will add it as an option. Thanks!
